name: Auto Update index.html

on:
  schedule:
    - cron: '0 16 * * *' # Runs daily at 4 PM UTC.
  workflow_dispatch:   # Optional: manual trigger

permissions: # <--- ADD THIS SECTION
  contents: write # <--- Grant write permission for contents

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download index.html from private repo
        run: |
          curl -H "Authorization: token ${{ secrets.PAT }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L \
               -o index.html \
               https://api.github.com/repos/porcupine-tech/dhsourcerepo/contents/index.html
          
          if [ ! -f index.html ]; then
            echo "Error: index.html was not downloaded. Check PAT permissions or URL."
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add index.html
          git commit -m "Auto-update index.html on $(date -u)" || echo "No changes to commit"
          git push
